# Generated by Django 5.2.3 on 2025-06-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arcana', models.CharField(choices=[('Major', 'Старші аркани'), ('Minor', 'Молодші аркани')], max_length=10)),
                ('suit', models.CharField(blank=True, choices=[('Wands', 'Жезли'), ('Cups', 'Кубки'), ('Swords', 'Мечі'), ('Pentacles', 'Пентаклі')], max_length=20, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
            ],
        ),
    ]
