# Generated by Django 5.2.3 on 2025-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='reversed_description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис у перевернутому положенні'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='arcana',
            field=models.CharField(choices=[('Major', 'Старші аркани'), ('Minor', 'Молодші аркани')], max_length=10, verbose_name='Аркана'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Повний опис'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='suit',
            field=models.CharField(blank=True, choices=[('Wands', 'Жезли'), ('Cups', 'Кубки'), ('Swords', 'Мечі'), ('Pentacles', 'Пентаклі')], max_length=20, null=True, verbose_name='Масть'),
        ),
    ]
