# Generated by Django 5.2.3 on 2025-06-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tarotcard_reversed_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='full_description_reversed',
            field=models.TextField(blank=True, null=True, verbose_name='Повний опис у перевернутому положенні'),
        ),
    ]
