# Generated by Django 5.2.3 on 2025-06-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_readinghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarotcard',
            old_name='description',
            new_name='short_description',
        ),
    ]
