# Generated by Django 5.2.3 on 2025-06-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_description_tarotcard_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarotcard',
            old_name='reversed_description',
            new_name='short_description_reversed',
        ),
    ]
