# Generated by Django 5.2.3 on 2025-07-11 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_readinghistory_ai_prediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('short_description_reversed', models.TextField()),
                ('full_description_reversed', models.TextField()),
                ('image', models.ImageField(upload_to='runes/')),
            ],
        ),
        migrations.CreateModel(
            name='RuneOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rune')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
