# Generated by Django 5.2.3 on 2025-07-15 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rune_runeoftheday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rune',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='RuneReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reversed', models.BooleanField(default=False)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('ai_prediction', models.TextField()),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rune')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
